/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/components/UserPopup': RouteRecordInfo<'/admin/components/UserPopup', '/admin/components/UserPopup', Record<never, never>, Record<never, never>>,
    '/admin/pages/user-mgmt': RouteRecordInfo<'/admin/pages/user-mgmt', '/admin/pages/user-mgmt', Record<never, never>, Record<never, never>>,
    'ui-examples': RouteRecordInfo<'ui-examples', '/examples', Record<never, never>, Record<never, never>>,
    '/examples/button': RouteRecordInfo<'/examples/button', '/examples/button', Record<never, never>, Record<never, never>>,
    '/examples/chart': RouteRecordInfo<'/examples/chart', '/examples/chart', Record<never, never>, Record<never, never>>,
    '/examples/chart-js': RouteRecordInfo<'/examples/chart-js', '/examples/chart-js', Record<never, never>, Record<never, never>>,
    '/examples/datepicker': RouteRecordInfo<'/examples/datepicker', '/examples/datepicker', Record<never, never>, Record<never, never>>,
    '/examples/editor-example': RouteRecordInfo<'/examples/editor-example', '/examples/editor-example', Record<never, never>, Record<never, never>>,
    '/examples/file': RouteRecordInfo<'/examples/file', '/examples/file', Record<never, never>, Record<never, never>>,
    '/examples/form': RouteRecordInfo<'/examples/form', '/examples/form', Record<never, never>, Record<never, never>>,
    '/examples/grid': RouteRecordInfo<'/examples/grid', '/examples/grid', Record<never, never>, Record<never, never>>,
    '/examples/icon-example': RouteRecordInfo<'/examples/icon-example', '/examples/icon-example', Record<never, never>, Record<never, never>>,
    '/examples/popup': RouteRecordInfo<'/examples/popup', '/examples/popup', Record<never, never>, Record<never, never>>,
    '/examples/tree': RouteRecordInfo<'/examples/tree', '/examples/tree', Record<never, never>, Record<never, never>>,
    'date-picker': RouteRecordInfo<'date-picker', '/examples/vue-date-picker', Record<never, never>, Record<never, never>>,
    '/globe/': RouteRecordInfo<'/globe/', '/globe', Record<never, never>, Record<never, never>>,
    '/map/': RouteRecordInfo<'/map/', '/map', Record<never, never>, Record<never, never>>,
    '/system/announcement/': RouteRecordInfo<'/system/announcement/', '/system/announcement', Record<never, never>, Record<never, never>>,
    '/system/announcement/[id]': RouteRecordInfo<'/system/announcement/[id]', '/system/announcement/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/system/announcement/admin-[id]': RouteRecordInfo<'/system/announcement/admin-[id]', '/system/announcement/admin-:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/system/announcement/admin-index': RouteRecordInfo<'/system/announcement/admin-index', '/system/announcement/admin-index', Record<never, never>, Record<never, never>>,
    '/system/announcement/create': RouteRecordInfo<'/system/announcement/create', '/system/announcement/create', Record<never, never>, Record<never, never>>,
    '/system/faq/': RouteRecordInfo<'/system/faq/', '/system/faq', Record<never, never>, Record<never, never>>,
    '/system/faq/[id]': RouteRecordInfo<'/system/faq/[id]', '/system/faq/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/system/faq/admin-[id]': RouteRecordInfo<'/system/faq/admin-[id]', '/system/faq/admin-:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/system/faq/admin-index': RouteRecordInfo<'/system/faq/admin-index', '/system/faq/admin-index', Record<never, never>, Record<never, never>>,
    '/system/faq/create': RouteRecordInfo<'/system/faq/create', '/system/faq/create', Record<never, never>, Record<never, never>>,
    '/system/qna/': RouteRecordInfo<'/system/qna/', '/system/qna', Record<never, never>, Record<never, never>>,
    '/system/qna/[id]': RouteRecordInfo<'/system/qna/[id]', '/system/qna/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/system/qna/admin-[id]': RouteRecordInfo<'/system/qna/admin-[id]', '/system/qna/admin-:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/system/qna/admin-index': RouteRecordInfo<'/system/qna/admin-index', '/system/qna/admin-index', Record<never, never>, Record<never, never>>,
    '/system/qna/create': RouteRecordInfo<'/system/qna/create', '/system/qna/create', Record<never, never>, Record<never, never>>,
  }
}
