/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AttachmentInput: typeof import('./components/AttachmentInput.vue')['default']
    BasicSelectBox: typeof import('./components/BasicSelectBox.vue')['default']
    ChartJsBarChart: typeof import('./components/chartJs/BarChart.vue')['default']
    ChartJsDoughnutChart: typeof import('./components/chartJs/DoughnutChart.vue')['default']
    ChartJsLineChart: typeof import('./components/chartJs/LineChart.vue')['default']
    CodeViewer: typeof import('./components/CodeViewer.vue')['default']
    CommonModal: typeof import('./components/CommonModal.vue')['default']
    CustomInput: typeof import('./components/CustomInput.vue')['default']
    Editor: typeof import('./components/Editor.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSidebarMenu: typeof import('./components/ElSidebarMenu.vue')['default']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTimeSelect: typeof import('element-plus/es')['ElTimeSelect']
    FileUpload: typeof import('./components/FileUpload.vue')['default']
    FormItem: typeof import('./components/FormItem.vue')['default']
    Globe: typeof import('./components/Globe.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    LayoutFooter: typeof import('./components/LayoutFooter.vue')['default']
    LayoutHeader: typeof import('./components/LayoutHeader.vue')['default']
    LayoutSidebar: typeof import('./components/LayoutSidebar.vue')['default']
    NoData: typeof import('./components/NoData.vue')['default']
    Pagination: typeof import('./components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./components/SearchForm.vue')['default']
    SearchItem: typeof import('./components/SearchItem.vue')['default']
    Tab: typeof import('./components/Tab.vue')['default']
    TreeSection: typeof import('./components/TreeSection.vue')['default']
  }
}
